lib/dona_libros_web/router.ex
defmodule DonaLibrosWeb.Router do
  use DonaLibrosWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", DonaLibrosWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create, :delete],
                                              singleton: true
    resources "/books", BookController
  end

  # Other scopes may use custom stacks.
  # scope "/api", DonaLibrosWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: DonaLibrosWeb.Telemetry
    end
  end

  defp authenticate_user(conn, _) do
    case get_session(conn, :user_id) do
      nil ->
        conn
        |> Phoenix.Controller.put_flash(:error, "Login required")
        |> Phoenix.Controller.redirect(to: "/")
        |> halt()
      user_id ->
        assign(conn, :current_user, DonaLibros.Accounts.get_user!(user_id))
    end
  end
end

lib/dona_libros_web/views/layout_view.ex
defmodule DonaLibrosWeb.LayoutView do
  use DonaLibrosWeb, :view

  def title() do
    "DonaLibros | A Book-Lending Library"
  end
end

lib/dona_libros_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= title() %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <%= render(DonaLibrosWeb.LayoutView, "navbar.html", conn: @conn) %>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>

lib/dona_libros_web/templates/layout/navbar.html.eex
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">

    <%= link "DonaLibros", to: Routes.page_path(@conn, :index), class: "navbar-item" %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">

        <%= link "Books", to: Routes.book_path(@conn, :index), class: "navbar-item" %>

    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">

          <%= link "Sign up", to: Routes.user_path(@conn, :new), class: "button is-primary" %>

          <%= link "Log in", to: Routes.session_path(@conn, :new), class: "button is-light" %>

        </div>
      </div>
    </div>
  </div>
</nav>